apiVersion: v1
kind: Service
metadata:
 name: test-product
spec:
 type: NodePort
 selector:
   app: Pfe-test-front
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 80
   targetPort: 80
   nodePort: 32221
